import type { Question } from "./types"

export const questions: Question[] = [
  // 1. Profil du Patient
  {
    id: 2,
    field: "age_years",
    question: "Âge (Années)",
    icon: "👤",
    type: "number",
    required: true,
    validation: { min: 0, max: 120 },
    suggestions: [
      { label: "0", value: 0 }, { label: "1", value: 1 }, { label: "2", value: 2 },
      { label: "5", value: 5 }, { label: "10", value: 10 }, { label: "20", value: 20 },
      { label: "30", value: 30 }, { label: "40", value: 40 }, { label: "50", value: 50 },
    ],
  },
  {
    id: 3,
    field: "age_months",
    question: "Âge (Mois)",
    icon: "👶",
    type: "number",
    required: true,
    validation: { min: 0, max: 11 },
    visibleIf: (data) => (data.age_years || 0) < 5,
    suggestions: [
      { label: "1m", value: 1 }, { label: "3m", value: 3 }, { label: "6m", value: 6 }, { label: "9m", value: 9 },
    ],
  },
  {
    id: 4,
    field: "gender",
    question: "Sexe",
    icon: "⚤",
    type: "radio",
    required: true,
    options: [
      { label: "Masculin (M)", value: "M" },
      { label: "Féminin (F)", value: "F" },
    ],
  },
  {
    id: 5,
    field: "poids",
    question: "Poids (kg)",
    icon: "⚖️",
    type: "number",
    required: true,
    validation: { min: 1, max: 200 },
    suggestions: [
      { label: "5kg", value: 5 }, { label: "10kg", value: 10 }, { label: "15kg", value: 15 },
      { label: "20kg", value: 20 }, { label: "40kg", value: 40 }, { label: "60kg", value: 60 },
      { label: "70kg", value: 70 }, { label: "80kg", value: 80 },
    ],
  },

  // Branchement Enfant < 5 ans
  {
    id: 6,
    field: "incapable_boire_teter",
    question: "L'enfant est-il incapable de boire ou de téter ?",
    icon: "🍼",
    type: "radio",
    required: true,
    options: [
      { label: "Oui", value: true },
      { label: "Non", value: false },
    ],
    visibleIf: (data) => (data.age_years || 0) < 5,
  },
  {
    id: 7,
    field: "vomit_tout",
    question: "L'enfant vomit-il tout ce qu'il consomme ?",
    icon: "🤮",
    type: "radio",
    required: true,
    options: [
      { label: "Oui", value: true },
      { label: "Non", value: false },
    ],
    visibleIf: (data) => (data.age_years || 0) < 5,
  },
  {
    id: 8,
    field: "perimetre_brachial_muac",
    question: "Périmètre Brachial (MUAC en mm)",
    icon: "💪",
    type: "number",
    required: true,
    validation: { min: 50, max: 250 },
    visibleIf: (data) => (data.age_years || 0) < 5,
    helpText: "Indicateur de malnutrition sévère",
    suggestions: [
      { label: "110", value: 110 }, { label: "115", value: 115 }, { label: "125", value: 125 }, { label: "135", value: 135 },
    ],
  },

  // Branchement Grossesse (F > 13 ans)
  {
    id: 9,
    field: "enceinte",
    question: "La patiente est-elle enceinte ?",
    icon: "🤰",
    type: "radio",
    required: true,
    options: [
      { label: "Oui", value: true },
      { label: "Non", value: false },
    ],
    visibleIf: (data) => data.gender === "F" && (data.age_years || 0) > 13,
  },
  {
    id: 10,
    field: "trimestre",
    question: "Trimestre de grossesse",
    icon: "🗓️",
    type: "radio",
    required: true,
    options: [
      { label: "1er Trimestre", value: 1 },
      { label: "2ème Trimestre", value: 2 },
      { label: "3ème Trimestre", value: 3 },
    ],
    visibleIf: (data) => !!data.enceinte,
  },
  {
    id: 11,
    field: "derniere_date_regles",
    question: "Date des dernières règles",
    icon: "📅",
    type: "date",
    required: false,
    visibleIf: (data) => !!data.enceinte,
  },

  // 2. Localisation
  {
    id: 12,
    field: "district",
    question: "District Sanitaire",
    icon: "🗺️",
    type: "synced-select",
    required: true,
  },
  {
    id: 13,
    field: "region",
    question: "Région",
    icon: "📍",
    type: "synced-select",
    required: true,
    dependsOn: "district",
  },
  {
    id: 14,
    field: "commune",
    question: "Commune / Sous-Préfecture",
    icon: "🏠",
    type: "synced-select",
    required: true,
    dependsOn: "region",
  },
  {
    id: 15,
    field: "geolocation",
    question: "Coordonnées GPS",
    icon: "📡",
    type: "geolocation",
    required: false,
    helpText: "Récupération automatique du kiosque",
  },
  {
    id: 16,
    field: "usage_moustiquaire",
    question: "Dormez-vous sous une moustiquaire imprégnée ?",
    icon: "🕸️",
    type: "radio",
    required: true,
    options: [
      { label: "Oui", value: true },
      { label: "Non", value: false },
    ],
  },

  // 3. Signes Vitaux
  {
    id: 17,
    field: "temperature_c",
    question: "Température Corporelle (°C)",
    icon: "🌡️",
    type: "number",
    required: true,
    validation: { min: 30, max: 45 },
    helpText: "Alerte si ≥ 39.5°C",
    suggestions: [
      { label: "37.0°C", value: 37.0 }, { label: "38.0°C", value: 38.0 }, { label: "38.5°C", value: 38.5 },
      { label: "39.0°C", value: 39.0 }, { label: "39.5°C", value: 39.5 }, { label: "40.0°C", value: 40.0 },
    ],
  },
  {
    id: 18,
    field: "spo2_pct",
    question: "Saturation en Oxygène (SpO2 %)",
    icon: "🫁",
    type: "number",
    required: true,
    validation: { min: 50, max: 100 },
    helpText: "Critique si < 90%",
    suggestions: [
      { label: "98%", value: 98 }, { label: "95%", value: 95 }, { label: "92%", value: 92 }, { label: "88%", value: 88 },
    ],
  },
  {
    id: 19,
    field: "fc_bpm",
    question: "Fréquence Cardiaque (BPM)",
    icon: "❤️",
    type: "number",
    required: true,
    suggestions: [
      { label: "60", value: 60 }, { label: "70", value: 70 }, { label: "80", value: 80 }, { label: "100", value: 100 }, { label: "120", value: 120 },
    ],
  },
  {
    id: 20,
    field: "fr_pm",
    question: "Fréquence Respiratoire (PM)",
    icon: "💨",
    type: "number",
    required: true,
    helpText: "Indicateur d'acidose si élevé",
    suggestions: [
      { label: "16", value: 16 }, { label: "20", value: 20 }, { label: "30", value: 30 }, { label: "40", value: 40 },
    ],
  },
  {
    id: 21,
    field: "pa_systolique",
    question: "Tension Systolique",
    icon: "🩺",
    type: "number",
    required: true,
    suggestions: [
      { label: "90", value: 90 }, { label: "100", value: 100 }, { label: "110", value: 110 }, { label: "120", value: 120 }, { label: "140", value: 140 },
    ],
  },
  {
    id: 22,
    field: "pa_diastolique",
    question: "Tension Diastolique",
    icon: "🩺",
    type: "number",
    required: true,
    suggestions: [
      { label: "60", value: 60 }, { label: "70", value: 70 }, { label: "80", value: 80 }, { label: "90", value: 90 },
    ],
  },

  // 4. Symptômes
  {
    id: 23,
    field: "symptoms_check",
    question: "Quels sont vos symptômes ?",
    icon: "🤒",
    type: "checkbox",
    required: false,
    checkboxes: [
      { label: "Fièvre", field: "fievre" },
      { label: "Troubles de la conscience", field: "troubles_conscience" },
      { label: "Convulsions", field: "convulsions" },
      { label: "Céphalées (Maux de tête)", field: "cephalees" },
      { label: "Nausées / Vomissements", field: "nausees_vomissements" },
      { label: "Diarrhée", field: "diarhee" },
      { label: "Douleurs Articulaires", field: "douleurs_articulaires" },
      { label: "Fatigue intense / Prostration", field: "fatigue" },
    ],
  },

  // Branchement Fièvre
  {
    id: 24,
    field: "duree_fievre_jours",
    question: "Depuis combien de jours avez-vous la fièvre ?",
    icon: "⏳",
    type: "number",
    required: true,
    visibleIf: (data) => !!data.fievre,
    suggestions: [
      { label: "1j", value: 1 }, { label: "2j", value: 2 }, { label: "3j", value: 3 }, { label: "5j", value: 5 }, { label: "7j", value: 7 },
    ],
  },
  {
    id: 25,
    field: "fievre_cyclique",
    question: "La fièvre est-elle cyclique (va et vient) ?",
    icon: "🔄",
    type: "radio",
    required: true,
    options: [
      { label: "Oui", value: true },
      { label: "Non", value: false },
    ],
    visibleIf: (data) => !!data.fievre,
  },
]
